apiVersion: v1
kind: Service
metadata:
  name: ezyevent-api-service
  labels:
    app: ezyevent-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ezyevent-api
  sessionAffinity: None
