apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezyevent-api-deployment
  labels:
    app: ezyevent-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ezyevent-api
  template:
    metadata:
      labels:
        app: ezyevent-api
    spec:
      containers:
        - name: ezyevent-api
          image: gcr.io/ezyevents/main-api:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ezyevent-api-service
  labels:
    app: ezyevent-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ezyevent-api
  sessionAffinity: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezyevent-location-api-deployment
  labels:
    app: ezyevent-location-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ezyevent-location-api
  template:
    metadata:
      labels:
        app: ezyevent-location-api
    spec:
      containers:
        - name: ezyevent-location-api
          image: gcr.io/ezyevents/location-api:v3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ezyevent-location-api-service
  labels:
    app: ezyevent-location-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ezyevent-location-api
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  labels:
    app: web-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: ezyevent-location-api
          image: gcr.io/ezyevents/web-ui:v3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  labels:
    app: web-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 80
  selector:
    app: web-ui
  sessionAffinity: None
